# Witdh of the maze
# Valid: 1 to 300
WIDTH = 20

# Height of the maze
# Valid: 1 to 150
HEIGHT = 20

# Entry point of the maze
# Valid: (x,y) or just x,y
ENTRY = 0,0

# Exit point of the maze
# Valid: (x,y) or just x,y
EXIT = 19,19

# The output of the file
OUTPUT_FILE = output.txt

# True or False for perfect maze
# Valid: 0/1 or True/False or yes/no or y/n
PERFECT = False

# Seed of the first maze
# Just an integer value
SEED = 42

# Animation of the maze
# Valid: 0/1 or True/False or yes/no or y/n
ANIMATION = True

# Algorithm to generate the maze
# Valid: 'DFS', 'BFS', 'ASTAR' or 'AUTO'
ALGO = BFS
